### PR TITLE
Support for function keys and related combos

### PR DESCRIPTION
**Pull request by tseeker**
It should now be possible to use sequences that include function keys (or shift/control/meta + function keys).

### CODE REVIEW

**Comment by liuchengxu** [comment]
Look great, could you also add some examples in README/doc since I actually haven't tried these keys and rarely use them daily?

**Comment by tseeker** [comment]
I don't really know where to put it in the README. The patch really just allows `vim-which-key` to function with mappings such as this:

```
nmap <silent> <Leader><S-F12> :set paste!<cr>
```
It doesn't change the way one uses `vim-which-key` at all.

**Comment by liuchengxu** [comment]
Using the combos like `<C-*>`, `<M-*>`, `<S-*>` correctly is not always easy, I have seen quite a few people having issues with them when using vim-which-key, so I hope we can have a chance to elaborate or at least give an example for the usage of the key combinations, this PR seems to a nice starting point. We could add a new section under `Examples`?

```diff
 - Refer to [space-vim](https://github.com/liuchengxu/space-vim/blob/master/core/autoload/spacevim/map/leader.vim) for more detailed example.
 
+##### Example for key combinations
+
+```vim
+" Function key
+nmap <silent> <Leader><F12>   :set paste!<cr>
+nmap <silent> <Leader><S-F12> :set paste!<cr>
+nmap <silent> <Leader><C-F12> :set paste!<cr>
+nmap <silent> <Leader><M-F12> :set paste!<cr>
+```
```

**Comment by liuchengxu** [comment]
Merged, thank you.

**Pull request merged**
