### PR TITLE
Add group_dicts_together_option

### PR DESCRIPTION
**Pull request by BrotifyPacha**
Add an option to make grouping dictionary items configurable. Requested in #191.

### CODE REVIEW

**Comment by liuchengxu** [comment]
LGTM.

@OliverLew Can you see if this patch helps #191?

**Review by bew — COMMENTED** [review]
Shouldn't
`g:which_key_group_dicts_at`
be called
`g:which_key_group_dicts_at_end`
or
`g:which_key_group_dicts_at_the_end`
instead?

Because `g:which_key_group_dicts_at` does not make much sense to me as a boolean.

Or if you want to keep that name, the value should not be a boolean like 0 or 1 but an enum like `start` / `end`.

What do you think?

**Comment by liuchengxu** [comment]
@bew makes a good point, and I have a further proposal:

```viml
if exists('g:which_key_group_dicts') && g:which_key_group_dicts != ''
  " ......
  if g:which_key_group_dicts ==? 'start'
    " ......
  else
    " ......
  endif
endif
```

then only one option has to be added.

**Comment by OliverLew** [comment]
The patch works. As a user, I also think that a single option might be better, with three choices `beginning/before`, `end/after` and `mixed`, or `0`, `1` and `2`.

**Comment by BrotifyPacha** [comment]
As suggested, combined two options into single one. Think that it's a great idea.

**Review by liuchengxu — CHANGES_REQUESTED** [review]
Can you please fix the tab as we use space here? Otherwise looks good to me.

**Comment by liuchengxu** [comment]
Merged, thank you! :beers:

**Pull request merged**
