### PR TITLE
Fix #199

### LINKED ISSUE #199: [bug] conflict with fastfold.vim
```vim
" $ uname -r
" 5.13.8-arch1-1
" $ has nvim
" ✓ nvim 0.5.0
" $ has python
" ✓ python 3.9.6
" $ vi test.vim
set runtimepath=$VIMRUNTIME,~/.local/share/nvim/repos/github.com/Konfekt/FastFold,~/.local/share/nvim/repos/github.com/liuchengxu/vim-which-key
nnoremap <nowait> z :<C-u>WhichKey 'z'<CR>
" $ vi -u test.vim demo.vim
```

this is demo.vim:
```vim
" Interaction {{{1 "
" UI {{{2 "
" liuchengxu/vim-which-key {{{3 "
" 3}}} liuchengxu/vim-which-key "
" 2}}} UI "

" KeyMap {{{2 "
" lyokha/vim-xkbswitch {{{3 "
" 3}}} lyokha/vim-xkbswitch "
" 2}}} KeyMap "
" 1}}} Interaction "
" ex: foldmethod=marker
```

after `vi -u test.vim demo.vim`
Screenshot from 2021-08-14 22-30-47
after `3ggl`, the folder was opened.
Screenshot from 2021-08-14 22-31-19
after `2dd`, a folder was deleted.
Screenshot from 2021-08-14 22-32-36

after `z`, wait to the popup window, vim-which-key will give you a popup window to prompt what hotkey has been mapped.
Screenshot from 2021-08-14 22-32-44
after `j`, it should jump to next folder, however:
Screenshot from 2021-08-14 22-32-47
some lines were deleted. this is a bug.

thanks.

<https://github.com/Konfekt/FastFold/issues/67>

### PR DESCRIPTION
**Pull request by Freed-Wu**
Remove all onoremaps

### CODE REVIEW

**Comment by liuchengxu** [comment]
I'm unsure it's a great decision to simply ignore the omaps. To fix it properly, you might want to check out how the visual mappings are handled.

https://github.com/liuchengxu/vim-which-key/blob/da2934fcd36350b871ed8ccd54c8eae3a0dfc8ae/autoload/which_key/mappings.vim#L65-L71

**Comment by Freed-Wu** [comment]
I believe now it is a good solution.

**Comment by Freed-Wu** [comment]
I have used this change for a month and have not yet found any side effects. Perhaps we should let more people test it? Thanks.

**Comment by liuchengxu** [comment]
@Freed-Wu Let's get it merged and see how it goes.

**Pull request merged**
